language: perl

install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n IO::Prompt 
  - cpanm -n Module::Build
  - cpanm -n MojoX::Log::Log4perl
  - cpanm -n Mojolicious
  - cpanm -n Sub::Exporter
  - cpanm -n JSON::XS
  - cpanm -n YAML::XS
  - cpanm -n List::MoreUtils
  - cpanm -n File::ShareDir
  - cpanm -n IO::Scalar
  - cpanm -n File::HomeDir
  - cpanm -n PlugAuth::Lite
  - cpanm -n Test::Clustericious::Cluster
  - cpanm -n Test::Pod::Coverage
  - cpanm -n Pod::Coverage
  - cpanm -n Rose::Planter
  - cpanm -n DBD::SQLite
  - cpanm -n DateTime::Format::DateParse
  - cpanm -n DateTime::Format::ISO8601
  - cpanm -n File::ReadBackwards
  - cpanm -n Hash::Merge
  - cpanm -n Data::Rmap
  - cpanm -n Log::Log4perl::Appender::TAP
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true

script: dzil test -v

perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

sudo: false
