language: perl

install:
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

script:
  - prove -lv
  - dzil install --install-command='cpanm -n -v .'
  - perl corpus/test_from_git https://github.com/clustericious/PlugAuth.git
  - perl corpus/test_from_git https://github.com/clustericious/Yars.git
  - perl corpus/test_from_git https://github.com/clustericious/Test-Clustericious-Cluster.git
  - perl corpus/test_from_git https://github.com/clustericious/Clustericious-Admin.git

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

sudo: false
