language: perl

install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n IO::Prompt Sub::Identify Module::Build MojoX::Log::Log4perl Log::Log4perl::Appender::TAP Log::Log4perl::CommandLine Mojolicious Sub::Exporter
  - cpanm -n JSON::MaybeXS YAML::XS List::MoreUtils File::ShareDir File::HomeDir Test::Clustericious::Cluster DateTime::Format::DateParse DateTime::Format::ISO8601
  - cpanm -n File::ReadBackwards Hash::Merge Data::Rmap

script:
  - prove -lv
  - dzil install --install-command='cpanm -n -v .'
  - perl corpus/test_from_git git@github.com:clustericious/PlugAuth.git
  - perl corpus/test_from_git git@github.com:clustericious/Yars.git
  - perl corpus/test_from_git git@github.com:clustericious/Test-Clustericious-Cluster.git
  - perl corpus/test_from_git git@github.com:clustericious/Clustericious-Admin.git

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

sudo: false
