language: perl
sudo: false

install:
  - cpanm Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  # Filesys::Df is needed for Yars (Dynamic prereq)
  # AnyEvent::Open3::Simple is needed for plackup test
  - cpanm -n Filesys::Df AnyEvent::Open3::Simple

script:
  - prove -lv
  - dzil install --install-command='cpanm -n -v .'
  - perl corpus/test_from_git https://github.com/clustericious/PlugAuth.git
  - perl corpus/test_from_git https://github.com/clustericious/Yars.git
  - perl corpus/test_from_git https://github.com/clustericious/Clustericious-RouteBuilder-Dancer2.git 5.014
  - perl corpus/test_from_git https://github.com/clustericious/Test-Clustericious-Cluster.git
  - perl corpus/test_from_git https://github.com/clustericious/App-clad.git

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
