---
abstract: 'A framework for RESTful processing systems.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  IO::Scalar: '0'
  Module::Build: '0.3601'
  PlugAuth::Lite: '0'
  Test::Clustericious::Cluster: '0.17'
  autodie: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Clustericious
no_index:
  directory:
    - share
    - example
requires:
  Data::Rmap: '0'
  DateTime::Format::DateParse: '0'
  DateTime::Format::ISO8601: '0'
  File::HomeDir: '0.91'
  File::ReadBackwards: '0'
  File::ShareDir: '0'
  File::Slurp: '0'
  Hash::Merge: '0'
  JSON::XS: '0'
  List::MoreUtils: '0'
  Log::Log4perl: '0'
  Log::Log4perl::Appender::TAP: '0.02'
  Module::Build: '0.3601'
  MojoX::Log::Log4perl: '0'
  Mojolicious: '5.40'
  Path::Class: '0'
  Sub::Exporter: '0'
  Term::Prompt: '0'
  Test::Builder::Module: '0'
  Test::More: '0'
  YAML::XS: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/plicease/clustericious/issues
  homepage: http://perl.wdlabs.com/Clustericious/
  repository: git://github.com/plicease/clustericious.git
version: '0.9941'
