#!/usr/bin/perl

use strict;
use warnings;
use autodie;
use lib './lib';
use Clustericious;

my $in;
my $out;

open($in, '<', 'Changes');
open($out, '>', 'Changes.tmp');

print $out scalar <$in>;
print $out scalar <$in>;

print $out sprintf("%-8s%s", $Clustericious::VERSION, `date`);
print $out $_ for <$in>;

close $in;
close $out;

rename 'Changes.tmp', 'Changes';
