=head1 NAME

Clustericious::Command::Hypnotoad

=head1 DESCRIPTION

Start a hypnotoad webserver.

=head1 SEE ALSO

Mojo::Server::Hypnotoad

=cut

package Clustericious::Command::Hypnotoad;
use Log::Log4perl qw/:easy/;

use Clustericious::App;
use Clustericious::Config;
use Mojo::Server::Hypnotoad;
use Data::Dumper;
use Cwd qw/abs_path/;
use base 'Mojo::Command';

use strict;
use warnings;

__PACKAGE__->attr(description => "Start a hypnotad web server.");

__PACKAGE__->attr(usage => <<EOT);
Usage $0: hypnotoad
No options are available.  The 'hypnotoad' entry in the config file
is used for configuration.
EOT

sub run {
    my $self = shift;
    # args are ignored, since hypnotoad doesn't take command line arguments.

    my $conf = Clustericious::Config->new($ENV{MOJO_APP})->hypnotoad;
    my $conf_file = abs_path($ENV{HYPNOTOAD_CONFIG} || "hypnotoad.conf");
    my %conf = %$conf;
    my $conf_string = Data::Dumper->Dump([\%conf],["conf"]);
    DEBUG "Starting hypnotoad (executable: $ENV{MOJO_EXE}, config: $conf_file)";
    DEBUG "Config : $conf_string";
    open my $fp, ">", $conf_file or die "Cannoy write to $conf_file";
    print $fp "## This file is autogenerated, any changes will be lost.\n";
    print $fp "## It was created when running $ENV{MOJO_EXE}\n";
    print $fp "## The contents reflect the 'hypnotoad' entry for that application.\n";
    print $fp "## To change the location of this file, set the HYPNOTOAD_CONFIG environment variable.\n";
    print $fp "\n\n$conf_string\n";
    system("hypnotoad","--config",$conf_file,$ENV{MOJO_EXE})==0 or die "error starting hypnotoad : $!";
}


1;

